Repository Gudsfile/tracksy, pull requests merged in 2025-08, with the labels that each got.

#57 ci(synthetic-datasets): add type checker
  .github/workflows/test-synthetic-datasets.yml
  synthetic-datasets/pyproject.toml
  synthetic-datasets/synthetic_datasets/models/spotify.py
  synthetic-datasets/uv.lock
Labels: ci/cd, [synthetic-datasets]

#58 docs: refresh readme
  .github/img/tracksy_demo.gif
  README.md
  app/README.md
  synthetic-datasets/README.md
Labels: documentation

#96 docs: add pull request template
  .github/PULL_REQUEST_TEMPLATE/default.md
Labels: documentation, [ [ meta ] ]

#94 refactor(app): move function to its own file
  app/src/db/queries/constants.ts
  app/src/db/queries/insertFilesInDatabase.ts
  app/src/db/queries/insertUrlInDatabase.ts
  app/src/hooks/useDemo.ts
Labels: refactor, [ app ]

#97 docs(): add License file
  LICENSE
Labels: documentation

#95 docs: add badges
  README.md
Labels: documentation, [ [ meta ] ]
